### ISSUE TITLE
Ça compile pas côté Satellite

### ISSUE THREAD

**Issue by Koryphon** [Locoduino/Locoduinodrome#1]
```
Aiguille.h: In member function 'virtual uint8_t Aiguille::EEPROM_chargement(int)':
Aiguille.h:31: error: no matching function for call to 'EEPROMClass::get(int&, unsigned int*, unsigned int)'
   EEPROM.get(addr, &this->posDroit, sizeof(unsigned int));
                                                         ^
Aiguille.h:31:57: note: candidate is:
In file included from Satellite.h:34:0,
                 from /Volumes/DevLoco/Locoduinodrome/Satellite/Satellite.ino:6:
/Users/koryphon/Library/Arduino15/packages/arduino/hardware/avr/1.6.20/libraries/EEPROM/src/EEPROM.h:130:31: note: template<class T> T& EEPROMClass::get(int, T&)
     template< typename T > T &get( int idx, T &t ){
                               ^
/Users/koryphon/Library/Arduino15/packages/arduino/hardware/avr/1.6.20/libraries/EEPROM/src/EEPROM.h:130:31: note:   template argument deduction/substitution failed:
```

**Comment by Trusty77** [comment]
Compile with IDE 1.8.5...
